from _typeshed import Incomplete
from google.auth._credentials_base import _BaseCredentials
from typing import Any, Mapping

class Credentials(_BaseCredentials):
    def __init__(self) -> None:
        ...
    async def apply(self, headers: Mapping[str, str], token: str | None = None) -> None:
        ...
    async def refresh(self, request: Any) -> None:
        ...
    async def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None:
        ...

class StaticCredentials(Credentials):
    token: str
    def __init__(self, token: str) -> None:
        ...
    async def refresh(self, request: Any) -> None:
        ...
    async def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None:
        ...

class AnonymousCredentials(Credentials):
    async def refresh(self, request: Any) -> None:
        ...
    async def apply(self, headers: Mapping[str, str], token: str | None = None) -> None:
        ...
    async def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None:
        ...