from google.auth.crypt import base

class RSAVerifier(base.Verifier):
    def __init__(self, public_key) -> None: ...
    def verify(self, message: bytes, signature: bytes) -> bool: ...
    @classmethod
    def from_string(cls, public_key: str | bytes) -> RSAVerifier: ...

class RSASigner(base.Signer, base.FromServiceAccountMixin):
    def __init__(self, private_key, key_id: str | None = None) -> None: ...
    @property
    def key_id(self) -> str | None: ...
    def sign(self, message: bytes) -> bytes: ...
    @classmethod
    def from_string(cls, key: str | bytes, key_id: str | None = None) -> RSASigner: ...
