import datetime
from typing import Any, Mapping, Optional, Sequence, Union

async def jwt_grant(request: Any, token_uri: str, assertion: str, can_retry: bool = True) -> tuple[str, Optional[datetime.datetime], dict[str, Any]]: ...
async def id_token_jwt_grant(request: Any, token_uri: str, assertion: str, can_retry: bool = True) -> tuple[str, Optional[datetime.datetime], dict[str, Any]]: ...
async def refresh_grant(request: Any, token_uri: str, refresh_token: str, client_id: str, client_secret: str, scopes: Optional[Sequence[str]] = None, rapt_token: Optional[str] = None, can_retry: bool = True) -> tuple[str, Optional[str], Optional[datetime.datetime], dict[str, Any], Optional[str]]: ...