import abc
from _typeshed import Incomplete
from typing import Any, Mapping, Optional, Sequence, Union
import datetime

def jwt_grant(request: Any, token_uri: str, assertion: str, can_retry: bool = True) -> tuple[str, Optional[datetime.datetime], dict[str, Any]]: ...
def call_iam_generate_id_token_endpoint(request: Any, iam_id_token_endpoint: str, signer_email: str, audience: str, access_token: str, universe_domain: str = ...) -> tuple[str, datetime.datetime]: ...
def id_token_jwt_grant(request: Any, token_uri: str, assertion: str, can_retry: bool = True) -> tuple[str, Optional[datetime.datetime], dict[str, Any]]: ...
def refresh_grant(request: Any, token_uri: str, refresh_token: str, client_id: str, client_secret: str, scopes: Optional[Sequence[str]] = None, rapt_token: Optional[str] = None, can_retry: bool = True) -> tuple[str, str, Optional[datetime.datetime], dict[str, Any]]: ...