import google.auth.transport
from typing import Any, Mapping, Optional, Sequence, Union

async def verify_token(id_token: Union[str, bytes], request: google.auth.transport.Request, audience: Optional[str] = None, certs_url: str = ..., clock_skew_in_seconds: int = 0) -> Mapping[str, Any]: ...
async def verify_oauth2_token(id_token: Union[str, bytes], request: google.auth.transport.Request, audience: Optional[str] = None, clock_skew_in_seconds: int = 0) -> Mapping[str, Any]: ...
async def verify_firebase_token(id_token: Union[str, bytes], request: google.auth.transport.Request, audience: Optional[str] = None, clock_skew_in_seconds: int = 0) -> Mapping[str, Any]: ...
async def fetch_id_token(request: google.auth.transport.Request, audience: str) -> str: ...