import datetime
from typing import Any, Mapping, Optional, Sequence, Union

async def get_rapt_token(request: Any, client_id: str, client_secret: str, refresh_token: str, token_uri: str, scopes: Optional[Sequence[str]] = None) -> str: ...
async def refresh_grant(request: Any, token_uri: str, refresh_token: str, client_id: str, client_secret: str, scopes: Optional[Sequence[str]] = None, rapt_token: Optional[str] = None, enable_reauth_refresh: bool = False) -> tuple[str, Optional[str], Optional[datetime.datetime], dict[str, Any], Optional[str]]: ...