from _typeshed import Incomplete
from google.auth import credentials
import datetime
from typing import Any, Mapping, Optional, Sequence

class Credentials(credentials.ReadOnlyScoped, credentials.CredentialsWithQuotaProject):
    token: Optional[str]
    expiry: Optional[datetime.datetime]
    def __init__(self, token: Optional[str], refresh_token: Optional[str] = None, id_token: Optional[str] = None, token_uri: Optional[str] = None, client_id: Optional[str] = None, client_secret: Optional[str] = None, scopes: Optional[Sequence[str]] = None, default_scopes: Optional[Sequence[str]] = None, quota_project_id: Optional[str] = None, expiry: Optional[datetime.datetime] = None, rapt_token: Optional[str] = None, refresh_handler: Optional[Any] = None, enable_reauth_refresh: bool = False, granted_scopes: Optional[Sequence[str]] = None, trust_boundary: Optional[str] = None, universe_domain: str = ..., account: Optional[str] = None) -> None: ...
    @property
    def refresh_token(self) -> Optional[str]: ...
    @property
    def scopes(self) -> Optional[Sequence[str]]: ...
    @property
    def granted_scopes(self) -> Optional[Sequence[str]]: ...
    @property
    def token_uri(self) -> Optional[str]: ...
    @property
    def id_token(self) -> Optional[str]: ...
    @property
    def client_id(self) -> Optional[str]: ...
    @property
    def client_secret(self) -> Optional[str]: ...
    @property
    def requires_scopes(self) -> bool: ...
    @property
    def rapt_token(self) -> Optional[str]: ...
    @property
    def refresh_handler(self) -> Optional[Any]: ...
    @refresh_handler.setter
    def refresh_handler(self, value: Optional[Any]) -> None: ...
    @property
    def account(self) -> str: ...
    def get_cred_info(self) -> Optional[Mapping[str, str]]: ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def with_token_uri(self, token_uri: str) -> 'Credentials': ...
    def with_account(self, account: str) -> 'Credentials': ...
    def with_universe_domain(self, universe_domain: str) -> 'Credentials': ...
    def refresh(self, request: Any) -> None: ...
    @classmethod
    def from_authorized_user_info(cls, info: Mapping[str, str], scopes: Optional[Sequence[str]] = None) -> 'Credentials': ...
    @classmethod
    def from_authorized_user_file(cls, filename: str, scopes: Optional[Sequence[str]] = None) -> 'Credentials': ...
    def to_json(self, strip: Optional[Sequence[str]] = None) -> str: ...

class UserAccessTokenCredentials(credentials.CredentialsWithQuotaProject):
    def __init__(self, account: Optional[str] = None, quota_project_id: Optional[str] = None) -> None: ...
    def with_account(self, account: str) -> 'UserAccessTokenCredentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'UserAccessTokenCredentials': ...
    token: Optional[str]
    def refresh(self, request: Any) -> None: ...
    def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None: ...