import datetime
from collections.abc import Sequence
from typing import Any

RUN_CHALLENGE_RETRY_LIMIT: int

def is_interactive() -> bool: ...
def get_rapt_token(request: Any, client_id: str, client_secret: str, refresh_token: str, token_uri: str, scopes: Sequence[str] | None = None) -> str: ...
def refresh_grant(request: Any, token_uri: str, refresh_token: str, client_id: str, client_secret: str, scopes: Sequence[str] | None = None, rapt_token: str | None = None, enable_reauth_refresh: bool = False) -> tuple[str, str | None, datetime.datetime | None, dict[str, Any], str | None]: ...