from _typeshed import Incomplete
from google.auth import credentials
import datetime
from typing import Any, Mapping, Optional, Sequence

class Credentials(credentials.Signing, credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithTokenUri, credentials.CredentialsWithTrustBoundary):
    def __init__(self, signer: Any, service_account_email: str, token_uri: str, scopes: Optional[Sequence[str]] = None, default_scopes: Optional[Sequence[str]] = None, subject: Optional[str] = None, project_id: Optional[str] = None, quota_project_id: Optional[str] = None, additional_claims: Optional[Mapping[str, Any]] = None, always_use_jwt_access: bool = False, universe_domain: str = ..., trust_boundary: Optional[Mapping[str, str]] = None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'Credentials': ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> 'Credentials': ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def project_id(self) -> Optional[str]: ...
    @property
    def requires_scopes(self) -> bool: ...
    def with_scopes(self, scopes: Sequence[str], default_scopes: Optional[Sequence[str]] = None) -> 'Credentials': ...
    def with_always_use_jwt_access(self, always_use_jwt_access: bool) -> 'Credentials': ...
    def with_universe_domain(self, universe_domain: str) -> 'Credentials': ...
    def with_subject(self, subject: str) -> 'Credentials': ...
    def with_claims(self, additional_claims: Mapping[str, Any]) -> 'Credentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def with_token_uri(self, token_uri: str) -> 'Credentials': ...
    def with_trust_boundary(self, trust_boundary: Mapping[str, str]) -> 'Credentials': ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer(self) -> Any: ...
    @property
    def signer_email(self) -> str: ...
    def get_cred_info(self) -> Optional[Mapping[str, str]]: ...

class IDTokenCredentials(credentials.Signing, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithTokenUri):
    def __init__(self, signer: Any, service_account_email: str, token_uri: str, target_audience: str, additional_claims: Optional[Mapping[str, Any]] = None, quota_project_id: Optional[str] = None, universe_domain: str = ...) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'IDTokenCredentials': ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> 'IDTokenCredentials': ...
    def with_target_audience(self, target_audience: str) -> 'IDTokenCredentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'IDTokenCredentials': ...
    def with_token_uri(self, token_uri: str) -> 'IDTokenCredentials': ...
    token: Optional[str]
    expiry: Optional[datetime.datetime]
    def refresh(self, request: Any) -> None: ...
    @property
    def service_account_email(self) -> str: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer(self) -> Any: ...
    @property
    def signer_email(self) -> str: ...