from datetime import datetime
from typing import Any, Mapping, Optional, Union

def is_on_gce(request: Any) -> bool: ...
def detect_gce_residency_linux() -> bool: ...
def ping(request: Any, timeout: int = ..., retry_count: int = ...) -> bool: ...
def get(request: Any, path: str, root: str | None = None, params: Mapping[str, str] | None = None, recursive: bool = False, retry_count: int = 5, headers: Mapping[str, str] | None = None, return_none_for_not_found_error: bool = False, timeout: int = ...) -> Union[Mapping, str]: ...
def get_project_id(request: Any) -> str: ...
def get_universe_domain(request: Any) -> str: ...
def get_service_account_info(request: Any, service_account: str = 'default') -> Mapping: ...
def get_service_account_token(request: Any, service_account: str = 'default', scopes: Optional[Union[str, list[str]]] = None) -> tuple[str, datetime.datetime]: ...
