from _typeshed import Incomplete
from google.auth import credentials
from typing import Any, Mapping, Optional, Sequence
import datetime

class Credentials(credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithUniverseDomain, credentials.CredentialsWithTrustBoundary):
    def __init__(self, service_account_email: str = 'default', quota_project_id: str | None = None, scopes: Sequence[str] | None = None, default_scopes: Sequence[str] | None = None, universe_domain: str | None = None, trust_boundary: Mapping[str, str] | None = None) -> None: ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def requires_scopes(self) -> bool: ...
    @property
    def universe_domain(self) -> str: ...
    def get_cred_info(self) -> Mapping[str, str]: ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def with_scopes(self, scopes: Sequence[str], default_scopes: Sequence[str] | None = None) -> 'Credentials': ...
    def with_universe_domain(self, universe_domain: str) -> 'Credentials': ...
    def with_trust_boundary(self, trust_boundary: Mapping[str, str]) -> 'Credentials': ...

class IDTokenCredentials(credentials.CredentialsWithQuotaProject, credentials.Signing, credentials.CredentialsWithTokenUri):
    def __init__(self, request: Any, target_audience: str, token_uri: str | None = None, additional_claims: Mapping[str, Any] | None = None, service_account_email: str | None = None, signer: Any | None = None, use_metadata_identity_endpoint: bool = False, quota_project_id: str | None = None) -> None: ...
    def with_target_audience(self, target_audience: str) -> 'IDTokenCredentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'IDTokenCredentials': ...
    def with_token_uri(self, token_uri: str) -> 'IDTokenCredentials': ...
    token: str | None
    expiry: datetime.datetime | None
    def refresh(self, request: Any) -> None: ...
    @property
    def signer(self) -> Any: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def signer_email(self) -> str: ...
