import logging
from _typeshed import Incomplete
from datetime import datetime
from typing import Any, Mapping, Optional, Sequence, Union

REFRESH_THRESHOLD: Incomplete

def copy_docstring(source_class):
    def decorator(method):
        ... # implementation omitted
    return decorator
def parse_content_type(header_value: str) -> str: ...
def utcnow() -> datetime.datetime: ...
def utcfromtimestamp(timestamp: float) -> datetime.datetime: ...
def datetime_to_secs(value: datetime.datetime) -> int: ...
def to_bytes(value: Union[str, bytes], encoding: str = 'utf-8') -> bytes: ...
def from_bytes(value: Union[str, bytes]) -> str: ...
def update_query(url: str, params: Mapping[str, str], remove: Sequence[str] | None = None) -> str: ...
def scopes_to_string(scopes: Sequence[str]) -> str: ...
def string_to_scopes(scopes: Union[Sequence[str], str]) -> list[str]: ...
def padded_urlsafe_b64decode(value: Union[str, bytes]) -> bytes: ...
def unpadded_urlsafe_b64encode(value: Union[str, bytes]) -> bytes: ...
def get_bool_from_env(variable_name: str, default: bool = False) -> bool: ...
def is_python_3() -> bool: ...
def is_logging_enabled(logger: logging.Logger) -> bool: ...
def request_log(logger: logging.Logger, method: str, url: str, body: bytes | None, headers: Mapping[str, str] | None) -> None: ...
def response_log(logger: logging.Logger, response: Any) -> None: ...
