from google.auth import _credentials_async, jwt
import datetime
from typing import Any, Mapping, Optional, Sequence, Union

def encode(signer: Any, payload: Mapping[str, Any], header: Optional[Mapping[str, Any]] = None, key_id: Optional[str] = None) -> bytes: ...
def decode(token: Union[str, bytes], certs: Optional[Union[str, bytes, Mapping[str, Union[str, bytes]]]] = None, verify: bool = True, audience: Optional[Union[str, Sequence[str]]] = None) -> dict[str, Any]: ...

class Credentials(jwt.Credentials, _credentials_async.Signing, _credentials_async.Credentials):
    def __init__(self, signer: Any, issuer: str, subject: str, audience: Union[str, Sequence[str]], additional_claims: Optional[Mapping[str, Any]] = None, token_lifetime: int = ..., quota_project_id: Optional[str] = None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'Credentials': ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> 'Credentials': ...
    @classmethod
    def from_signing_credentials(cls, credentials: Any, audience: Union[str, Sequence[str]], **kwargs: Any) -> 'Credentials': ...
    def with_claims(self, issuer: Optional[str] = None, subject: Optional[str] = None, audience: Optional[Union[str, Sequence[str]]] = None, additional_claims: Optional[Mapping[str, Any]] = None) -> 'Credentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def refresh(self, request: Any) -> None: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> Any: ...
    @property
    def additional_claims(self) -> dict[str, Any]: ...

class OnDemandCredentials(jwt.OnDemandCredentials, _credentials_async.Signing, _credentials_async.Credentials):
    def __init__(self, signer: Any, issuer: str, subject: str, additional_claims: Optional[Mapping[str, Any]] = None, token_lifetime: int = ..., max_cache_size: int = ..., quota_project_id: Optional[str] = None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'OnDemandCredentials': ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> 'OnDemandCredentials': ...
    @classmethod
    def from_signing_credentials(cls, credentials: Any, **kwargs: Any) -> 'OnDemandCredentials': ...
    def with_claims(self, issuer: Optional[str] = None, subject: Optional[str] = None, additional_claims: Optional[Mapping[str, Any]] = None) -> 'OnDemandCredentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'OnDemandCredentials': ...
    @property
    def valid(self) -> bool: ...
    def refresh(self, request: Any) -> None: ...
    def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> Any: ...