import threading
from _typeshed import Incomplete

class RefreshThreadManager:
    def __init__(self) -> None: ...
    def start_refresh(self, cred: Incomplete, request: Incomplete) -> bool: ...
    def clear_error(self) -> None: ...

class RefreshThread(threading.Thread):
    _error_info: Incomplete
    def __init__(self, cred: Incomplete, request: Incomplete, **kwargs) -> None: ...
    def run(self) -> None: ...
