from _typeshed import Incomplete
from google.auth import credentials
from typing import Any, Mapping, Optional

class Credentials(credentials.Credentials):
    token: str
    def __init__(self, token: str) -> None: ...
    @property
    def expired(self) -> bool: ...
    @property
    def valid(self) -> bool: ...
    def refresh(self, request: Any) -> None: ...
    def apply(self, headers: Mapping[str, str], token: str | None = None) -> None: ...
    def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None: ...