from google.auth import credentials, crypt
from typing import Any, Optional, Sequence

class Signer(crypt.Signer):
    @property
    def key_id(self) -> None: ...
    def sign(self, message: bytes) -> bytes: ...

def get_project_id() -> str: ...

class Credentials(credentials.Scoped, credentials.Signing, credentials.CredentialsWithQuotaProject):
    def __init__(self, scopes: Sequence[str] | None = None, default_scopes: Sequence[str] | None = None, service_account_id: str | None = None, quota_project_id: str | None = None) -> None: ...
    def refresh(self, request: Any) -> None: ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def requires_scopes(self) -> bool: ...
    def with_scopes(self, scopes: Sequence[str], default_scopes: Sequence[str] | None = None) -> 'Credentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> Signer: ...