import abc
from dataclasses import dataclass
from google.auth import external_account
from typing import Optional, Union


class RequestSigner:
    def __init__(self, region_name: str) -> None: ...
    def get_request_options(self, aws_security_credentials: 'AwsSecurityCredentials', url: str, method: str, request_payload: str = '', additional_headers: dict[str, str] = {}) -> dict[str, str]: ...

@dataclass
class AwsSecurityCredentials:
    access_key_id: str
    secret_access_key: str
    session_token: Optional[str] = None

class AwsSecurityCredentialsSupplier(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def get_aws_security_credentials(self, context, request) -> 'AwsSecurityCredentials': ...
    @abc.abstractmethod
    def get_aws_region(self, context, request) -> str: ...

class _DefaultAwsSecurityCredentialsSupplier(AwsSecurityCredentialsSupplier):
    def __init__(self, credential_source: dict[str, str]) -> None: ...
    def get_aws_security_credentials(self, context, request) -> 'AwsSecurityCredentials': ...
    def get_aws_region(self, context, request) -> str: ...

class Credentials(external_account.Credentials):
    def __init__(self, audience: str, subject_token_type: str, token_url: str = ..., credential_source: dict[str, str] | None = None, aws_security_credentials_supplier: Union["AwsSecurityCredentialsSupplier", None] = None, *args, **kwargs) -> None: ...
    def retrieve_subject_token(self, request) -> str: ...
    @classmethod
    def from_info(cls, info: dict[str, str], **kwargs) -> 'Credentials': ...
    @classmethod
    def from_file(cls, filename: str, **kwargs) -> 'Credentials': ...