import abc
from _typeshed import Incomplete
from enum import Enum
from google.auth._credentials_base import _BaseCredentials
import datetime
from typing import Any, Mapping, Optional, Sequence

DEFAULT_UNIVERSE_DOMAIN: str
NO_OP_TRUST_BOUNDARY_LOCATIONS: list[str]
NO_OP_TRUST_BOUNDARY_ENCODED_LOCATIONS: str

class Credentials(_BaseCredentials, metaclass=abc.ABCMeta):
    expiry: Optional[datetime.datetime]
    def __init__(self) -> None: ...
    @property
    def expired(self) -> bool: ...
    @property
    def valid(self) -> bool: ...
    @property
    def token_state(self) -> TokenState: ...
    @property
    def quota_project_id(self) -> Optional[str]: ...
    @property
    def universe_domain(self) -> str: ...
    def get_cred_info(self) -> Optional[Mapping[str, str]]: ...
    @abc.abstractmethod
    def refresh(self, request: Any) -> None: ...
    def apply(self, headers: Mapping[str, str], token: Optional[str] = None) -> None: ...
    def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None: ...
    def with_non_blocking_refresh(self) -> None: ...

class CredentialsWithQuotaProject(Credentials, metaclass=abc.ABCMeta):
    def with_quota_project(self, quota_project_id: str) -> 'CredentialsWithQuotaProject': ...
    def with_quota_project_from_environment(self) -> 'CredentialsWithQuotaProject': ...

class CredentialsWithTokenUri(Credentials, metaclass=abc.ABCMeta):
    def with_token_uri(self, token_uri: str) -> 'CredentialsWithTokenUri': ...

class CredentialsWithUniverseDomain(Credentials, metaclass=abc.ABCMeta):
    def with_universe_domain(self, universe_domain: str) -> 'CredentialsWithUniverseDomain': ...

class CredentialsWithTrustBoundary(Credentials, metaclass=abc.ABCMeta):
    def with_trust_boundary(self, trust_boundary: Mapping[str, str]) -> 'CredentialsWithTrustBoundary': ...
    def apply(self, headers: Mapping[str, str], token: Optional[str] = None) -> None: ...
    def refresh(self, request: Any) -> None: ...

class AnonymousCredentials(Credentials):
    @property
    def expired(self) -> bool: ...
    @property
    def valid(self) -> bool: ...
    def refresh(self, request: Any) -> None: ...
    def apply(self, headers: Mapping[str, str], token: Optional[str] = None) -> None: ...
    def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None: ...

class ReadOnlyScoped(metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @property
    def scopes(self) -> Optional[Sequence[str]]: ...
    @property
    def default_scopes(self) -> Optional[Sequence[str]]: ...
    @property
    @abc.abstractmethod
    def requires_scopes(self) -> bool: ...
    def has_scopes(self, scopes: Sequence[str]) -> bool: ...

class Scoped(ReadOnlyScoped, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def with_scopes(self, scopes: Sequence[str], default_scopes: Optional[Sequence[str]] = None) -> 'Scoped': ...

def with_scopes_if_required(credentials: Credentials, scopes: Sequence[str], default_scopes: Optional[Sequence[str]] = None) -> Credentials: ...

class Signing(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    @abc.abstractmethod
    def signer_email(self) -> Optional[str]: ...
    @property
    @abc.abstractmethod
    def signer(self) -> Any: ...

class TokenState(Enum):
    FRESH = 1
    STALE = 2
    INVALID = 3
