from _typeshed import Incomplete
from google.auth import credentials
from typing import Any, Mapping, Optional, Sequence, Union
import datetime

class CredentialAccessBoundary:
    def __init__(self, rules: Sequence[AccessBoundaryRule] = []) -> None: ...
    @property
    def rules(self) -> tuple[AccessBoundaryRule, ...]: ...
    @rules.setter
    def rules(self, value: Sequence[AccessBoundaryRule]) -> None: ...
    def add_rule(self, rule: AccessBoundaryRule) -> None: ...
    def to_json(self) -> dict[str, Any]: ...

class AccessBoundaryRule:
    def __init__(self, available_resource: str, available_permissions: Sequence[str], availability_condition: AvailabilityCondition | None = None) -> None: ...
    @property
    def available_resource(self) -> str: ...
    @available_resource.setter
    def available_resource(self, value: str) -> None: ...
    @property
    def available_permissions(self) -> tuple[str, ...]: ...
    @available_permissions.setter
    def available_permissions(self, value: Sequence[str]) -> None: ...
    @property
    def availability_condition(self) -> AvailabilityCondition | None: ...
    @availability_condition.setter
    def availability_condition(self, value: AvailabilityCondition | None) -> None: ...
    def to_json(self) -> dict[str, Any]: ...

class AvailabilityCondition:
    def __init__(self, expression: str, title: str | None = None, description: str | None = None) -> None: ...
    @property
    def expression(self) -> str: ...
    @expression.setter
    def expression(self, value: str) -> None: ...
    @property
    def title(self) -> str | None: ...
    @title.setter
    def title(self, value: str | None) -> None: ...
    @property
    def description(self) -> str | None: ...
    @description.setter
    def description(self, value: str | None) -> None: ...
    def to_json(self) -> dict[str, str]: ...

class Credentials(credentials.CredentialsWithQuotaProject):
    def __init__(self, source_credentials: credentials.Credentials, credential_access_boundary: CredentialAccessBoundary, quota_project_id: str | None = None, universe_domain: str = ...) -> None: ...
    token: str | None
    expiry: datetime.datetime | None
    def refresh(self, request: Any) -> None: ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...