import abc
from dataclasses import dataclass
from google.auth import credentials
import datetime
from typing import Any, Mapping, Optional, Sequence

@dataclass
class SupplierContext:
    subject_token_type: str
    audience: str

class Credentials(credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithTokenUri, credentials.CredentialsWithTrustBoundary, metaclass=abc.ABCMeta):
    def __init__(self, audience: str, subject_token_type: str, token_url: str, credential_source: Mapping[str, Any], service_account_impersonation_url: Optional[str] = None, service_account_impersonation_options: Optional[Mapping[str, Any]] = None, client_id: Optional[str] = None, client_secret: Optional[str] = None, token_info_url: Optional[str] = None, quota_project_id: Optional[str] = None, scopes: Optional[Sequence[str]] = None, default_scopes: Optional[Sequence[str]] = None, workforce_pool_user_project: Optional[str] = None, universe_domain: str = ..., trust_boundary: Optional[Mapping[str, str]] = None) -> None:
        ...  # implementation omitted
    @property
    def info(self) -> Mapping[str, Any]: ...
    @property
    def service_account_email(self) -> Optional[str]: ...
    @property
    def is_user(self) -> bool: ...
    @property
    def is_workforce_pool(self) -> bool: ...
    @property
    def requires_scopes(self) -> bool: ...
    @property
    def project_number(self) -> Optional[str]: ...
    @property
    def token_info_url(self) -> Optional[str]: ...
    def get_cred_info(self) -> Optional[Mapping[str, str]]: ...
    def with_scopes(self, scopes: Sequence[str], default_scopes: Optional[Sequence[str]] = None) -> 'Credentials': ...
    @abc.abstractmethod
    def retrieve_subject_token(self, request: Any) -> str: ...
    def get_project_id(self, request: Any) -> Optional[str]: ...
    def refresh(self, request: Any) -> None: ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def with_token_uri(self, token_uri: str) -> 'Credentials': ...
    def with_universe_domain(self, universe_domain: str) -> 'Credentials': ...
    def with_trust_boundary(self, trust_boundary: Mapping[str, str]) -> 'Credentials': ...
    @classmethod
    def from_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'Credentials': ...
    @classmethod
    def from_file(cls, filename: str, **kwargs: Any) -> 'Credentials': ...
