from _typeshed import Incomplete
from datetime import datetime

from google.auth import credentials
from typing import Any, Mapping, Optional, Sequence

class Credentials(credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.Signing, credentials.CredentialsWithTrustBoundary):
    token: str | None
    expiry: datetime.datetime
    def __init__(self, source_credentials: credentials.Credentials, target_principal: str, target_scopes: Sequence[str], delegates: Sequence[str] | None = None, subject: str | None = None, lifetime: int = ..., quota_project_id: str | None = None, iam_endpoint_override: str | None = None, trust_boundary: Mapping[str, str] | None = None) -> None: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def signer(self) -> Any: ...
    @property
    def requires_scopes(self) -> bool: ...
    def get_cred_info(self) -> Mapping[str, str] | None: ...
    def with_trust_boundary(self, trust_boundary: Mapping[str, str]) -> 'Credentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def with_scopes(self, scopes: Sequence[str], default_scopes: Sequence[str] | None = None) -> 'Credentials': ...
    @classmethod
    def from_impersonated_service_account_info(cls, info: Mapping[str, Any], scopes: Sequence[str] | None = None) -> 'Credentials': ...

class IDTokenCredentials(credentials.CredentialsWithQuotaProject):
    def __init__(self, target_credentials: Credentials, target_audience: str | None = None, include_email: bool = False, quota_project_id: str | None = None) -> None: ...
    def from_credentials(self, target_credentials: Credentials, target_audience: str | None = None) -> 'IDTokenCredentials': ...
    def with_target_audience(self, target_audience: str) -> 'IDTokenCredentials': ...
    def with_include_email(self, include_email: bool) -> 'IDTokenCredentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'IDTokenCredentials': ...
    token: str | None
    expiry: datetime.datetime | None
    def refresh(self, request: Any) -> None: ...
