import google.auth.credentials
import datetime
from typing import Any, Mapping, Optional, Sequence, Union

from google.auth import crypt


def encode(signer: crypt.Signer, payload: Mapping[str, Any], header: Mapping[str, Any] | None = None, key_id: str | None = None) -> bytes: ...
def decode_header(token: str | bytes) -> dict[str, Any]: ...
def decode(token: str | bytes, certs: str | bytes | Mapping[str, str | bytes] | None = None, verify: bool = True, audience: str | Sequence[str] | None = None, clock_skew_in_seconds: int = 0) -> dict[str, Any]: ...

class Credentials(google.auth.credentials.Signing, google.auth.credentials.CredentialsWithQuotaProject):
    def __init__(self, signer: crypt.Signer, issuer: str, subject: str, audience: str | Sequence[str], additional_claims: Mapping[str, Any] | None = None, token_lifetime: int = ..., quota_project_id: str | None = None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'Credentials': ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> 'Credentials': ...
    @classmethod
    def from_signing_credentials(cls, credentials: google.auth.credentials.Signing, audience: str | Sequence[str], **kwargs: Any) -> 'Credentials': ...
    def with_claims(self, issuer: str | None = None, subject: str | None = None, audience: str | Sequence[str] | None = None, additional_claims: Mapping[str, Any] | None = None) -> 'Credentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'Credentials': ...
    def refresh(self, request: Any) -> None: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> crypt.Signer: ...
    @property
    def additional_claims(self) -> dict[str, Any]: ...

class OnDemandCredentials(google.auth.credentials.Signing, google.auth.credentials.CredentialsWithQuotaProject):
    def __init__(self, signer: crypt.Signer, issuer: str, subject: str, additional_claims: Mapping[str, Any] | None = None, token_lifetime: int = ..., max_cache_size: int = ..., quota_project_id: str | None = None) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, Any], **kwargs: Any) -> 'OnDemandCredentials': ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> 'OnDemandCredentials': ...
    @classmethod
    def from_signing_credentials(cls, credentials: google.auth.credentials.Signing, **kwargs: Any) -> 'OnDemandCredentials': ...
    def with_claims(self, issuer: str | None = None, subject: str | None = None, additional_claims: Mapping[str, Any] | None = None) -> 'OnDemandCredentials': ...
    def with_quota_project(self, quota_project_id: str) -> 'OnDemandCredentials': ...
    @property
    def valid(self) -> bool: ...
    def refresh(self, request: Any) -> None: ...
    def before_request(self, request: Any, method: str, url: str, headers: Mapping[str, str]) -> None: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> crypt.Signer: ...