import aiohttp
from _typeshed import Incomplete
from google.auth import transport
from typing import Any, Mapping, Optional, Sequence, Union
import datetime

class _CombinedResponse(transport.Response):
    def __init__(self, response: Any) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> Mapping[str, str]: ...
    @property
    def data(self) -> bytes: ...
    async def raw_content(self) -> bytes: ...
    async def content(self) -> bytes: ...

class _Response(transport.Response):
    def __init__(self, response: Any) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> Mapping[str, str]: ...
    @property
    def data(self) -> bytes: ...

class Request(transport.Request):
    session: aiohttp.ClientSession | None
    def __init__(self, session: aiohttp.ClientSession | None = None) -> None: ...
    async def __call__(self, url: str, method: str = 'GET', body: bytes | None = None, headers: Mapping[str, str] | None = None, timeout: Union[float, aiohttp.ClientTimeout] | None = None, **kwargs: Any) -> transport.Response: ...

class AuthorizedSession(aiohttp.ClientSession):
    credentials: Any
    def __init__(self, credentials: Any, refresh_status_codes: Sequence[int] = ..., max_refresh_attempts: int = ..., refresh_timeout: int | None = None, auth_request: Request | None = None, auto_decompress: bool = False, **kwargs: Any) -> None: ...
    async def request(self, method: str, url: str, data: bytes | None = None, headers: Mapping[str, str] | None = None, max_allowed_time: float | None = None, timeout: Union[float, aiohttp.ClientTimeout] | None = None, auto_decompress: bool = False, **kwargs: Any) -> transport.Response: ...
