from _typeshed import Incomplete

SIGN_CALLBACK_CTYPE: Incomplete

def load_offload_lib(offload_lib_path: str) -> Incomplete: ...
def load_signer_lib(signer_lib_path: str) -> Incomplete: ...
def load_provider_lib(provider_lib_path: str) -> Incomplete: ...
def get_sign_callback(signer_lib: Incomplete, config_file_path: str) -> Incomplete: ...
def get_cert(signer_lib: Incomplete, config_file_path: str) -> bytes: ...

class CustomTlsSigner:
    def __init__(self, enterprise_cert_file_path: str) -> None: ...
    def load_libraries(self) -> None: ...
    def set_up_custom_key(self) -> None: ...
    def should_use_provider(self) -> bool: ...
    def attach_to_ssl_context(self, ctx: Incomplete) -> None: ...
