from google.auth import transport

class Response(transport.Response):
    def __init__(self, response) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def data(self) -> bytes: ...

class Request(transport.Request):
    def __call__(self, url: str, method: str = 'GET', body: bytes | None = None, headers: dict[str, str] | None = None, timeout: int | None = None, **kwargs) -> Response: ...
