from typing import Any

CONTEXT_AWARE_METADATA_PATH: str
CERTIFICATE_CONFIGURATION_DEFAULT_PATH: str

def get_client_ssl_credentials(generate_encrypted_key: bool = False, context_aware_metadata_path: str = ..., certificate_config_path: str | None = None) -> tuple[bool, bytes | None, bytes | None, bytes | None]: ...
def get_client_cert_and_key(client_cert_callback: Any = None) -> tuple[bool, bytes | None, bytes | None]: ...
def decrypt_private_key(key: bytes, passphrase: bytes) -> bytes: ...
def check_use_client_cert() -> bool: ...
def check_parameters_for_unauthorized_response(cached_cert: bytes) -> tuple[bytes, bytes, str, str]: ...
def call_client_cert_callback() -> tuple[bytes, bytes]: ...
