from typing import Any

import grpc

class AuthMetadataPlugin(grpc.AuthMetadataPlugin):
    def __init__(self, credentials: Any, request: Any, default_host: str | None = None) -> None: ...
    def __call__(self, context: Any, callback: Any) -> None: ...

def secure_authorized_channel(credentials: Any, request: Any, target: str, ssl_credentials: grpc.ChannelCredentials | None = None, client_cert_callback: Any | None = None, **kwargs: Any) -> grpc.Channel: ...

class SslCredentials:
    def __init__(self) -> None: ...
    @property
    def ssl_credentials(self) -> grpc.ChannelCredentials: ...
    @property
    def is_mtls(self) -> bool: ...