from collections.abc import Sequence
from typing import Any, Union

import requests
import requests.adapters
import types
from _typeshed import Incomplete
from google.auth import transport

class _Response(transport.Response):
    def __init__(self, response: Any) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def data(self) -> bytes: ...

class TimeoutGuard:
    remaining_timeout: Incomplete
    def __init__(self, timeout: Union[float, tuple[float, float]] | None, timeout_error_type: type[Exception] = requests.exceptions.Timeout) -> None: ...
    def __enter__(self) -> 'TimeoutGuard': ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> bool | None: ...

class Request(transport.Request):
    session: requests.Session
    def __init__(self, session: requests.Session | None = None) -> None: ...
    def __del__(self) -> None: ...
    def __call__(self, url: str, method: str = 'GET', body: bytes | None = None, headers: dict[str, str] | None = None, timeout: int = ..., **kwargs: Any) -> transport.Response: ...

class _MutualTlsAdapter(requests.adapters.HTTPAdapter):
    def __init__(self, cert: bytes, key: bytes) -> None: ...
    def init_poolmanager(self, *args: Any, **kwargs: Any) -> None: ...
    def proxy_manager_for(self, *args: Any, **kwargs: Any) -> Any: ...

class _MutualTlsOffloadAdapter(requests.adapters.HTTPAdapter):
    signer: Incomplete
    def __init__(self, enterprise_cert_file_path: str) -> None: ...
    def init_poolmanager(self, *args: Any, **kwargs: Any) -> None: ...
    def proxy_manager_for(self, *args: Any, **kwargs: Any) -> Any: ...

class AuthorizedSession(requests.Session):
    credentials: Any
    def __init__(self, credentials: Any, refresh_status_codes: Sequence[int] = ..., max_refresh_attempts: int = ..., refresh_timeout: int | None = None, auth_request: Request | None = None, default_host: str | None = None) -> None: ...
    def configure_mtls_channel(self, client_cert_callback: Any | None = None) -> None: ...
    def request(self, method: str, url: str, data: bytes | None = None, headers: dict[str, str] | None = None, max_allowed_time: float | None = None, timeout: int = ..., **kwargs: Any) -> transport.Response: ...
    @property
    def is_mtls(self) -> bool: ...
    def close(self) -> None: ...