import types
from _typeshed import Incomplete
from typing import Any, Sequence

from google.auth import transport

RequestMethods: Incomplete

class _Response(transport.Response):
    def __init__(self, response: Any) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def data(self) -> bytes: ...

class Request(transport.Request):
    http: Incomplete
    def __init__(self, http: Any) -> None: ...
    def __call__(self, url: str, method: str = 'GET', body: bytes | None = None, headers: dict[str, str] | None = None, timeout: int | None = None, **kwargs: Any) -> transport.Response: ...

class AuthorizedHttp(RequestMethods):
    http: Any
    credentials: Any
    def __init__(self, credentials: Any, http: Any | None = None, refresh_status_codes: Sequence[int] = ..., max_refresh_attempts: int = ..., default_host: str | None = None) -> None: ...
    def configure_mtls_channel(self, client_cert_callback: Any | None = None) -> bool: ...
    def urlopen(self, method: str, url: str, body: bytes | None = None, headers: dict[str, str] | None = None, **kwargs: Any) -> transport.Response: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, traceback: types.TracebackType | None) -> bool | None: ...
    def __del__(self) -> None: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @headers.setter
    def headers(self, value: dict[str, str]) -> None: ...